config/routes.rb
Rails.application.routes.draw do
  get '/contact', to: "pages#contact"
  get '/privacy', to: "pages#privacy"
  get '/environmental', to: "pages#environmental"
  get '/terms_of_use', to: "pages#terms_of_use"
  get '/cookies', to: "pages#cookies"
  get '/about_us', to: "pages#about_us"
  get '/testomonials', to: "pages#testomonials"
  resources :line_items
  resources :carts
  resources :items
  devise_for :users, controllers: {
    registrations: "registrations"
  }
  root 'items#index'
  get '/billing', to: 'billing#show'
  resources :contact, only: [:create]

  get '/checkout', to: 'checkouts#show'
  scope '/checkout' do
    get 'cancel', to: 'checkouts#cancel', as: 'checkout_cancel'
    get 'success', to: 'checkouts#success', as: 'checkout_success'
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/shared/_banner_homepage.html.erb
<div class="home-page">
  <div id="main-banner" class="darken-overlay">
    <div class="darken-overlay">
      <div class="main-banner-container">
        <div class="wrapper" style="width: 100%;">
          <div class="wrapper-h1" >
            <h1 style="color: white;">Your first choice for Jewelry.<br>Online marketplace,<br>Built on rails</h1>
          </div>
          <div class="wrapper-button">
            <% unless user_signed_in? %>
              <br><br>
              <div id="button-to-subscription">
                <!-- <button onclick= "smoothScroll(document.getElementById('subsriptions'))" style="background: transparent; border: none;" > -->
                  <%= link_to "Products", items_path, :class => "btn btn-medium"%>
                </button>
              </div>
              <br><br>
            <% else %>
              <br><br>
              <%= link_to "Products", items_path, :class => "btn btn-medium"%>
              <br><br>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<style>
  // Specific CSS for your home-page
  $red: #F68787;
  $orange: #F8A978;
  $yellow: #F1EB9A;
  $green: #A4F6A5;
  .main-container{
    width: 100%;
    // height: calc(100vh - 120px);
    margin-bottom: 50px;
  }

  .padded-container{
    // width: 100px;
    margin-top: 50px;
  }

  .wrapper-h1 {
    margin-left: 10vh;
    height: 66.6%;
    h1 {
      letter-spacing: 2px;
      font-size: 1.5rem;

    }
  }

  .wrapper-button {
    height: 33.3%;
    text-align: center;
    .btn:hover {
      color: #4da8da;
    }
  }

  #main-banner {
    background:url("https://res.cloudinary.com/dk6tfvphu/image/upload/v1655746217/eleonora-JcL5sCUnBeI-unsplash_yikgsa.jpg");
    width: 100%;
    height: 60vh;
    // margin-left: -270px;
    background-size: cover;
    top: 0;
    z-index: -1;
  }

  .darken-overlay {
    width: 100%;
    height: 100%;
    // min-height: 100vh;
    background-color: rgba(0, 0, 0, 0.30);
  }

  .wrapper .btn-medium{
    // padding-left: 33px;
    font-family: "Roboto Cn", sans-serif;
    font-size: 3vmin;
    /* opacity: 1; */
    color: white;
    text-transform: uppercase;
    letter-spacing: 19px;
    font-weight: bolder;

    border: 1px solid;
  }

  .main-banner-container {
    display: flex;
    flex-direction: column;
    justify-content: center;
    align-items: baseline;
    height: 100%;
    // text-align: center;
    // position: relative;
    h1 {
      color: white;
      font-size: 5vmin;
    }
    p {
      color: white;
    }
  }

  #banner-typed-text {
    color: white;
    font-size: 36px;
    font-family: "Raleway", "sans-serif";
  }

  .overview-icon {
    font-size: 100px;
    padding-top: 20px;
    padding-bottom: 20px;
  }


  .home-font {
    font-size: 24px;
  }

  .home-top {
    margin: 50px;
  }


  .home-bottom {
    margin-bottom: 50px;
    padding-bottom: 10px;
  }

  .why-us {
    width: 100%;
    text-align: center;
    height: 20%;
    margin-top: 10px;
    hr {
      width: 60%;
      margin: auto;
      margin-top: 5px;
    }
  }


  :root {
    --surface-color: #fff;
    --curve: 40;
  }

  // * {
  //   box-sizing: border-box;
  // }

  body {
    // font-family: 'Noto Sans JP', sans-serif;
    background-color: none!important;
  }



  .video-section {
    position: relative;
    width: 75%;
    height: 50vh;
    display: flex;
    align-items: center;
    justify-content: center;
    overflow: hidden;
    margin: auto;
  }

  .video-section h1 {
    text-align: center;
    font-size: 6rem;
    font-family: "Roboto Cn", sans-serif;
    padding: 20px;
    margin: 15px;
    z-index: 1;
    opacity: 0.7;
    color: #effbfb;
  }

  .video-container {
    position: absolute;
    top: 0;
    left: 0;
    width: 100%;
  }

  .color-overlay {
    position: absolute;
    top: 0;
    left: 0;
    background-color: lightblue;
    width: 100%;
    height: 80vh;
    opacity: 0.5;
  }


  #carousel-one {
    background:url(image_path('home.jpg'));
    width: 100%;
    height: 100vh;
    // margin-left: -270px;
    background-size: cover;
    top: 0;
    z-index: -1;
  }

  #carousel-two {
    background:url(image_path('home-two.jpg'));
    width: 100%;
    height: 100vh;
    // margin-left: -270px;
    background-size: cover;
    top: 0;
    z-index: -1;
  }

  #carousel-three {
    background:url(image_path('home-three.jpg'));
    width: 100%;
    height: 100vh;
    // margin-left: -270px;
    background-size: cover;
    top: 0;
    z-index: -1;
  }

  .heading {
      text-align: center;
      color: #454343;
      font-size: 30px;
      font-weight: 700;
      position: relative;
      margin-bottom: 70px;
      text-transform: uppercase;
      z-index: 999;
  }
  .white-heading{
      color: #ffffff;
  }
  .heading:after {
      content: ' ';
      position: absolute;
      top: 100%;
      left: 50%;
      height: 40px;
      width: 180px;
      border-radius: 4px;
      transform: translateX(-50%);
      background: url(img/heading-line.png);
      background-repeat: no-repeat;
      background-position: center;
  }
  .white-heading:after {
      background: url(https://i.ibb.co/d7tSD1R/heading-line-white.png);
      background-repeat: no-repeat;
      background-position: center;
  }

  .heading span {
      font-size: 18px;
      display: block;
      font-weight: 500;
  }
  .white-heading span {
      color: #ffffff;
  }
  /*-----Testimonial-------*/

  .testimonial:after {
      position: absolute;
      top: -0 !important;
      left: 0;
      content: " ";
      background:url(image_path('testomonial.jpg'));
      background-size: 100% 100px;
      width: 100%;
      height: 100px;
      float: left;
      z-index: 99;
  }

  .testimonial {
      min-height: 600px;
      position: relative;
      // background-image: linear-gradient(to right, red , blue);


      background:url(image_path('testomonial.jpg'));
      padding-top: 50px;
      padding-bottom: 50px;
      background-position: center;
          background-size: cover;

  }

  #testimonial4 .carousel-inner:hover{
    cursor: -moz-grab;
    cursor: -webkit-grab;
  }
  #testimonial4 .carousel-inner:active{
    cursor: -moz-grabbing;
    cursor: -webkit-grabbing;
  }
  #testimonial4 .carousel-inner .item{
    overflow: hidden;
  }

  .testimonial4_indicators .carousel-indicators{
    left: 0;
    margin: 0;
    width: 100%;
    font-size: 0;
    height: 20px;
    bottom: 15px;
    padding: 0 5px;
    cursor: e-resize;
    overflow-x: auto;
    overflow-y: hidden;
    position: absolute;
    text-align: center;
    white-space: nowrap;
  }
  .testimonial4_indicators .carousel-indicators li{
    padding: 0;
    width: 14px;
    height: 14px;
    border: none;
    text-indent: 0;
    margin: 2px 3px;
    cursor: pointer;
    display: inline-block;
    background: #ffffff;
    -webkit-border-radius: 100%;
    border-radius: 100%;
  }
  .testimonial4_indicators .carousel-indicators .active{
    padding: 0;
    width: 14px;
    height: 14px;
    border: none;
    margin: 2px 3px;
    background-color: #9dd3af;
    -webkit-border-radius: 100%;
    border-radius: 100%;
  }
  .testimonial4_indicators .carousel-indicators::-webkit-scrollbar{
    height: 3px;
  }
  .testimonial4_indicators .carousel-indicators::-webkit-scrollbar-thumb{
    background: #eeeeee;
    -webkit-border-radius: 0;
    border-radius: 0;
  }

  .testimonial4_control_button .carousel-control{
    top: 175px;
    opacity: 1;
    width: 40px;
    bottom: auto;
    height: 40px;
    font-size: 10px;
    cursor: pointer;
    font-weight: 700;
    overflow: hidden;
    line-height: 38px;
    text-shadow: none;
    text-align: center;
    position: absolute;
    background: transparent;
    border: 2px solid #ffffff;
    text-transform: uppercase;
    -webkit-border-radius: 100%;
    border-radius: 100%;
    -webkit-box-shadow: none;
    box-shadow: none;
    // -webkit-transition: all 0.6s cubic-bezier(0.3,1,0,1);
    // transition: all 0.6s cubic-bezier(0.3,1,0,1);
  }
  .testimonial4_control_button .carousel-control.left{
    left: 7%;
    top: 50%;
    right: auto;
  }
  .testimonial4_control_button .carousel-control.right{
    right: 7%;
    top: 50%;
    left: auto;
  }
  .testimonial4_control_button .carousel-control.left:hover,
  .testimonial4_control_button .carousel-control.right:hover{
    color: #000;
    background: #fff;
    border: 2px solid #fff;
  }

  .testimonial4_header{
    top: 0;
    left: 0;
    bottom: 0;
    width: 550px;
    display: block;
    margin: 30px auto;
    text-align: center;
    position: relative;
  }
  .testimonial4_header h4{
    color: #ffffff;
    font-size: 30px;
    font-weight: 600;
    position: relative;
    letter-spacing: 1px;
    text-transform: uppercase;
  }

  .testimonial4_slide{
    top: 0;
    left: 0;
    right: 0;
    bottom: 0;
    width: 70%;
    margin: auto;
    padding: 20px;
    position: relative;
    text-align: center;
  }
  .testimonial4_slide img {
      top: 0;
      left: 0;
      right: 0;
      width: 136px;
      height: 136px;
      margin: auto;
      display: block;
      color: #f2f2f2;
      font-size: 18px;
      line-height: 46px;
      text-align: center;
      position: relative;
      border-radius: 50%;
      box-shadow: -6px 6px 6px rgba(0, 0, 0, 0.23);
      -moz-box-shadow: -6px 6px 6px rgba(0, 0, 0, 0.23);
      -o-box-shadow: -6px 6px 6px rgba(0, 0, 0, 0.23);
      -webkit-box-shadow: -6px 6px 6px rgba(0, 0, 0, 0.23);
  }
  .testimonial4_slide p {
      color: #ffffff;
      font-size: 20px;
      line-height: 1.4;
      margin: 40px 0 20px 0;
  }
  .testimonial4_slide h4 {
    color: #ffffff;
    font-size: 22px;
  }

  .testimonial .carousel {
    padding-bottom:50px;
  }

  /* ------testimonial  close-------*/
  //







</style>

app/views/shared/_contact_form.html.erb
<section class="contact-page-section">
  <div class="container mt-5 mb-5">
    <div class="inner-container">
      <div class="row clearfix">
        <!--Form Column-->
        <div class="form-column col-lg-8 col-sm-12 col-xs-12">
         <div class="inner-column">
               <!--Contact Form-->
          <div class="contact-form">
            <%= form_for Contact.new, url: contact_path do |f| %>
                 <div class="row clearfix">
                     <div class="form-group col-lg-6 col-sm-6 co-xs-12">
                      <%= f.text_field :name, placeholder: "name", class: "form-control", required: "true" %>
                     </div>
                     <div class="form-group col-lg-6 col-sm-6 co-xs-12">
                      <%= f.email_field :email, placeholder: "name@email.com", autocomplete: "email", class: "form-control", required: "true" %>
                     </div>
                     <div class="form-group col-lg-6 col-sm-6 co-xs-12">
                      <%= f.text_field :subject, class: "form-control", placeholder: "subject", required: "true" %>
                     </div>
                     <div class="form-group col-lg-6 col-sm-6 co-xs-12">
                      <%= f.text_field :phone, class: "form-control", placeholder: "phone" %>
                     </div>
                     <div class="form-group col-lg-12 col-sm-12 co-xs-12">
                      <%= f.text_area :message, class: "form-control", placeholder: "Write message in here...", required: "true" %>
                     </div>
                     <div class="field mb-3">
                       <%= flash[:recaptcha_error] %>
                       <%= recaptcha_tags %>
                     </div>
                     <div class="form-group col-lg-12 col-sm-12 co-xs-12">
                      <%= f.submit "Submit", class: "theme-btn btn-style-one" %>
                     </div>
                 </div>
             <% end %>
          </div>
          <!--End Contact Form-->
        </div>
      </div>
        <!--Info Column-->
        <div class="info-column col-lg-4 col-sm-12 col-xs-12">
         <div class="inner-column text-center">
          <h2 class="pb-1">Contact Info</h2>
            <ul class="list-info">
              <i class="fa fa-globe text-center" style="color:#24388d;font-size:30px;"></i>
              <li>Designed by Bond</li>
              <i class="fa fa-envelope text-center" style="color:#24388d;font-size:30px;"></i>
              <li>designed.by.bond@gmail.com</li>
              <li></li>
              <i class="fa fa-phone text-center pb-2" style="color:#24388d;font-size:30px;"></i><br>
              <a style="color:#24388d;font-size:18px;" href="tel:00447590745745" onclick="ga('send', 'event', { eventCategory: 'Contact', eventAction: 'Call', eventLabel: 'Mobile Button'});"><p class="call-button">+44 7590 745 745</p></a>
            </ul>
            <div class="row">
              <div class="col-12 text-center">
                <ul class="social-icons">
                  <%= mail_to "weigheasy2022@gmail.com" do %><i class="fa fa-envelope"></i><% end %>
                  <li><a class="facebook" href="#"><i class="fa fa-facebook-f"></i></a></li>
                  <li><a class="twitter" href="#"><i class="fa fa-twitter"></i></a></li>
                  <li><a class="whatsapp" href="#" target="blank"><i class="fa fa-whatsapp"></i></a></li>
                  <li><a class="linkedin" href="#"><i class="fa fa-linkedin"></i></a></li>
                </ul>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/shared/_flashes.html.erb
<% if !flash[:notice].blank? %>
  <div>
    <% flash.each do |type, msg| %>

      <div class="alert alert-info alert-dismissible fade show responsive-flash-padding" role="alert">
        <%= msg %>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      </div>
    <% end %>
  </div>
<% elsif !flash[:error].blank? %>
   <div>
      <% flash.each do |type, msg| %>
        <div class="alert alert-danger alert-dismissible fade show responsive-flash-padding" role="alert">
          <%= msg %>
          <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
      <% end %>
   </div>
<% elsif !flash[:warning].blank? %>
  <div>
    <% flash.each do |type, msg| %>
      <div class="alert alert-warning alert-dismissible fade show responsive-flash-padding" role="alert">
        <%= msg %>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      </div>
    <% end %>
  </div>
<% else !flash[:info].blank? %>
  <div>
    <% flash.each do |type, msg| %>
      <div class="alert alert-primary alert-dismissible fade show responsive-flash-padding" role="alert">
        <%= msg %>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      </div>
    <% end %>
  </div>
<% end %>
<style>
  <% if current_page?(root_path) %>
    @media screen and (max-width: 992px){
      .responsive-flash-padding {
        height: 80px;
        margin-left: 80px;
      }
    }
  <% else %>
    @media screen and (max-width: 992px){
      .responsive-flash-padding {
        height: 80px;
        margin-left: 80px;
        margin-top: -80px;
      }
    }
  <% end %>
  .alert {
    margin-bottom: 0px!important;
  }
</style>

app/views/shared/_footer.html.erb
<!-- Site footer -->

<!-- faking forum channels, room to add this feature later -->
<% forum_channels = ["Seeking advice on Jeweley", "Cleaning and maintaining", "How to ensure you order correct parts", "Looking for the correct Gem", "Help - looking for guidance on a new piece"]%>
<!-- faking blogs, room to add this feature later -->
<% blogs = ["A year in the life", "How to safely clean that heirloom", "Why choosing the right hardware is important", "How to take envoke change", "Future styles"]%>

<footer class="site-footer" >
  <div class="container">
    <div class="row">
      <div class="col-sm-12 col-lg-6">
        <h6>About</h6>
        <p class="text-justify"><i>AN E-COMMERSE SITE BUILT WITH RUBY ON RAILS </i> A web application for purchasing and selling Jewelery. The app uses Devise to handle users, Stripe for payments, AWS for image storage when creating items and recaptcha for the contact form - using a generic Gmail account to handle the email</p>
      </div>
      <div class="col-xs-6 col-lg-3">
        <h6>Forum channels</h6>
        <ul class="footer-links">
          <% forum_channels.map do |thread| %>
            <li><%= link_to "#{thread.truncate_words(5)}", root_path %></li>
          <% end %>
          <h6>Latest Blogs</h6>
            <% blogs.map do |blog| %>
              <li><%= link_to "#{blog.truncate_words(5)}", root_path %></li>
            <% end %>
        </ul>
      </div>
      <div class="col-xs-6 col-lg-3">
        <h6>Quick Links</h6>
        <ul class="footer-links">
          <li><%= link_to "Home Page", root_path %></li>
          <li><%= link_to "Contact us", contact_path %></li>
          <li><%= link_to "About us", about_us_path %></li>
          <li><%= link_to "View all testomonials", testomonials_path %></li>
          <li><%= link_to "Privacy Policy", privacy_path %></li>
          <li><%= link_to "Environmental Policy", environmental_path %></li>
          <li><%= link_to "Terms of use", terms_of_use_path %></li>
          <li><%= link_to "Cookie policy", cookies_path %></li>
          <li><a href="#">Sitemap</a></li>
        </ul>
      </div>
    </div>
  </div>
  <hr>
  <div class="container footer-padding">
    <div class="row">
      <div class="col-lg-8 col-sm-6 col-xs-12">
        <p class="copyright-text">Copyright &copy; 2022 <br>All Rights Reserved by Lorenzo.
     <!-- <a href="#">Scanfcode</a>. -->
        </p>
      </div>
      <div class="col-lg-4 col-sm-6 col-xs-12">
        <ul class="social-icons">
          <%= mail_to "weigheasy2022@gmail.com" do %><i class="fa fa-envelope"></i><% end %>
          <li><a class="facebook" href="#"><i class="fa fa-facebook-f"></i></a></li>
          <li><a class="twitter" href="#"><i class="fa fa-twitter"></i></a></li>
          <li><a class="whatsapp" href="#" target="blank"><i class="fa fa-whatsapp"></i></a></li>
          <li><a class="linkedin" href="#"><i class="fa fa-linkedin"></i></a></li>
        </ul>
      </div>
    </div>
  </div>
</footer>

app/views/shared/_navbar.html.erb
<!-- ?navbar for screens wider than 770px -->
<div class="nav-wrapper">
  <div class="nav-container d-none d-lg-block">
    <nav>
      <a href="https://designed-by-bond.herokuapp.com">
        <img alt="DBB" src="https://res.cloudinary.com/dk6tfvphu/image/upload/v1655745750/cb_dgbhpv.jpg" style="width: 150px; height:60px; margin-top: 5px; margin-bottom: 5px;">
      </a>
      <!-- below lines are for meilisearch - which doesn't work in production on heroku -->
      <!--
      </% if current_page?(items_path) %>
        <form class="d-flex">
          </%= form_with url: items_path, method: :get do |form| %>
            </%= form.search_field :query, class: "form-control me-2", type: "search", placeholder: "Search" %>
            </%= form.button "Search", class: "btn btn-outline-success", type: "submit" %>
          </% end %>
        </form>
      </% end %> -->
          <ul>
            <% if total_cart_items %>
              <%= link_to cart_path(@cart), class:"navbar-item button is-warning" do %>
              <span class="icon is-small">
                <i class="fa fa-shopping-cart"></i>
              </span>
              <span>Cart
                <%= cart_count_over_one %>
                </span>
              <% end %>
            <% end %>
            <% unless user_signed_in? %>
              <li><%= link_to "Login", new_user_session_path%></li>
              <li><%= link_to "Sign Up", new_user_registration_path%></li>
              <% else %>
              <!-- </%= link_to "ADMIN", admin_path, id: "admin_tag", class: "brand" if current_user.admin? %> -->
              <li><%= link_to "Home", root_path %></li>
              <li><%= link_to "Items", items_path %></li>
              <div class="avatar-container">
                <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle" id="navbarDarkDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                    <!-- </%= image_tag current_user.avatar_thumbnail, class: "avatar", alt: "avatar" %> -->
                    <%= image_tag "avatar.png", class: "avatar", alt: "avatar" %>
                  </a>
                  <ul class="dropdown-menu dropdown-menu-dark" aria-labelledby="navbarDarkDropdownMenuLink">
                    <!-- <li><a></%= link_to "Profile", profile_path, class: "dropdown-item" %></a></li> -->
                    <li><a><%= link_to "Edit", edit_user_registration_path, class: "dropdown-item" %></a></li>
                    <li><a><%= link_to "Sign Out", destroy_user_session_path, method: :delete, class: "dropdown-item"%></a></li>
                  </ul>
                </li>
              </div>
            <% end %>
          </ul>
      </nav>
  </div>
</div>

app/views/shared/_responsive_navbar.html.erb
<!-- hamburger icon for devices smaller than 770px wide -->
<div class="menu-wrap d-lg-none">
  <input type="checkbox" class="toggler">
  <div class="hamburger"><div></div></div>
  <div class="menu">
    <div>
      <div>
        <ul>
          <a href="https://designed-by-bond.herokuapp.com">
            <img alt="DBB" src="https://res.cloudinary.com/dk6tfvphu/image/upload/v1655745750/cb_dgbhpv.jpg" style="width: 100px; height:60px; margin-top: 20px; margin-bottom: 5px;">
          </a>
           <br><br>
            <% unless user_signed_in? %>
              <li><%= link_to "Login", new_user_session_path%></li>
              <li><%= link_to "Sign Up", new_user_registration_path%></li>
            <% else %>
              <div class="avatar-container">
                <div class="hamburger-avatar-sizing">
                 <li>
                   <%= image_tag "avatar.png", class: "avatar", alt: "avatar" %>
                   <br><br>
                 </li>
                </div>
              </div>
              <li><%= link_to "Home", root_path %></li>
              <li><%= link_to "Items", items_path %></li>
              <li><%= link_to "Edit user", edit_user_registration_path %></li>
              <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete%></li>
            <% end %>
        </ul>
      </div>
    </div>
  </div>
</div>

<!--  -->

app/views/shared/_testomonials.html.erb
<div id="carouselExampleCaptions" class="carousel slide" data-bs-ride="carousel">
    <div class="carousel-indicators">
      <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
      <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="1" aria-label="Slide 2"></button>
      <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="2" aria-label="Slide 3"></button>
    </div>
    <section class="testimonial text-center" >
      <div class="container">
        <div class="heading white-heading">Testimonials</div>
          <div class="carousel-inner" role="listbox">
            <div class="carousel-item active">
              <div class="testimonial4_slide">
                  <img src="https://res.cloudinary.com/weigheasy/image/upload/c_scale,w_240/v1642894216/Yacht_detfla.jpg" />
                  <p>Some convincing bo****ks</p>
                  <h4>Thomas Bond</h4>
              </div>
            </div>
            <div class="carousel-item">
              <div class="testimonial4_slide">
                  <img src="https://res.cloudinary.com/weigheasy/image/upload/v1644096850/alexander-hipp-iEEBWgY_6lA-unsplash_ag2st0.jpg" />
                  <p>Don't you just love jewelery</p>
                  <h4>Jonathon Barry</h4>
              </div>
            </div>
            <div class="carousel-item">
              <div class="testimonial4_slide">
                  <img src="https://i.ibb.co/8x9xK4H/team.jpg" class="img-circle img-responsive" />
                  <p>These guys know there stuff. 100% recommend</p>
                  <h4>James O'brian</h4>
              </div>
            </div>
          </div>
        </div>
        <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleCaptions"  data-bs-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="visually-hidden">Previous</span>
        </button>
        <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleCaptions"  data-bs-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="visually-hidden">Next</span>
        </button>
      </div>
    </section>
  </div>