config/routes.rb
Rails.application.routes.draw do
  get '/contact', to: "pages#contact"
  get '/privacy', to: "pages#privacy"
  get '/environmental', to: "pages#environmental"
  get '/terms_of_use', to: "pages#terms_of_use"
  get '/cookies', to: "pages#cookies"
  get '/about_us', to: "pages#about_us"
  get '/testomonials', to: "pages#testomonials"
  resources :line_items
  resources :carts
  resources :items
  devise_for :users, controllers: {
    registrations: "registrations"
  }
  root 'items#index'
  get '/billing', to: 'billing#show'
  resources :contact, only: [:create]

  get '/checkout', to: 'checkouts#show'
  scope '/checkout' do
    get 'cancel', to: 'checkouts#cancel', as: 'checkout_cancel'
    get 'success', to: 'checkouts#success', as: 'checkout_success'
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/item.rb
class Item < ApplicationRecord
  mount_uploader :image, ProductImageUploader
  # below lines are for meilisearch - which doesn't work in production on heroku
  # include MeiliSearch::Rails
  # extend Pagy::Meilisearch

  before_destroy :not_referenced_by_any_line_item
  has_many :line_items
  belongs_to :user, optional: true

  validates :title, :price, :brand, :product_code, :quantity_available, :description, presence: true
  # validates :description,length: { maximum: 1000, too_long: "%{count} characters is the maximum allowed."}
  validates :title, length: { maximum: 140, too_long: "%{count} characters is the maximum allowed."}
  validates :price, length: { maximum: 7 }

  BRAND = %w{ Yanma Mercury }
  AVAILABILITY = %w{ Available Unavailable }

  # below lines are for meilisearch - which doesn't work in production on heroku
  # meilisearch per_environment: true do
  #   attribute :title
  #   attribute :price
  #   attribute :review_rating
  #   attribute :review_count
  #   attribute :brand
  #   attribute :product_code
  #   attribute :availability
  #   attribute :quantity_available
  #   attribute :description
  #   attribute :user_id
  #   attribute :image
  #   attribute :stripe_item_id
  #   attribute :currency
  #   attribute :stripe_price_id

  #   attribute :created_at do
  #     created_at.to_i
  #   end

  #   filterable_attributes [ :brand ]
  #   sortable_attributes [:updated_at, :created_at ]
  # end

  def not_referenced_by_any_line_item
    unless line_items.empty?
      errors.add(:base, "Line items present")
      throw :abort
    end
  end


  # create stripe item and assign to this item
  after_create do
    item = Stripe::Product.create(name: title)
    price = Stripe::Price.create(product: item, unit_amount: self.price * 100, currency: self.currency)
    update(stripe_item_id: item.id, stripe_price_id: price.id)
  end

  # stripe keeps items and prices separately.
  # updating local prices would require to update or create stripe prices.
  # this is all additional complexity.
  # better just create new items.

  # after_update :create_and_assign_new_stripe_price, if: :saved_change_to_price?
  # after_update :create_and_assign_new_stripe_price, if: :saved_change_to_currency?

  # def create_and_assign_new_stripe_price
  #   price = Stripe::Price.create(item: self.stripe_item_id, unit_amount: self.price, currency: self.currency)
  #   update(stripe_price_id: price.id)
  # end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  before_action :set_item, only: %i[ show edit update destroy ]

  # GET /items or /items.json
  def index
    @items = Item.all
    @pagy, @items =pagy(@items, items: 10)
    # below is to use with meilisearch - which doesn't work in production on heroku
    # @items = Item.pagy_search(params[:query])
    # @pagy, @items= pagy_meilisearch(@items, items: 10)
  end

  # GET /items/1 or /items/1.json
  def show
  end

  # GET /items/new
  def new
    @item = current_user.items.build
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items or /items.json
  def create
    @item = current_user.items.build(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to item_url(@item), notice: "Item was successfully created." }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1 or /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to item_url(@item), notice: "Item was successfully updated." }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1 or /items/1.json
  def destroy
    @item.destroy

    respond_to do |format|
      format.html { redirect_to items_url, notice: "Item was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def item_params
      params.require(:item).permit(:title, :price, :review_rating, :review_count, :brand, :product_code, :availability, :quantity_available, :description, :image)
    end
end

app/helpers/items_helper.rb
module ItemsHelper
  def allowed_to_edit(item)
    user_signed_in? && current_user.id == item.user_id
    # || current_user.admin?
  end

  def product_availability(item)
    if item.quantity_available == "0"
      "Not in stock"
    else
      "In Stock"
    end
  end
end

app/views/items/_form.html.erb
<div class="columns">
  <div class="column is-12 is-centered">
    <%= simple_form_for @item, html: { multipart: true } do |f| %>
      <%= f.error_notification %>
       <div class="columns">
        <div class="field column">
          <div class="control">
            <%= f.input :title , required: true, input_html: { class: "input"}, wrapper: false, label_html: { class:"label" } %>
          </div>
        </div>
      </div>
      <div class="columns">
        <div class="field column is-6">
          <div class="control">
            <%= f.input :price, required: true, input_html: { class:"input", maxlength: 7  }, wrapper: false, label_html: { class:"label" } %>
          </div>
        </div>
        <div class="field column">
          <div class="control">
            <%= f.input :product_code , required: true, input_html: { class: "input"}, wrapper: false, label_html: { class:"label" } %>
          </div>
        </div>
      </div>
      <div class="field">
        <div class="control">
          <%= f.input :description, required: true, input_html: { class:"textarea" }, wrapper: false, label_html: { class:"label" } %>
        </div>
      </div>
      <div class="columns">
        <div class="field column is-4">
          <div class="control">
            <%= f.input :quantity_available, required: true, input_html: { class:"input", maxlength: 7  }, wrapper: false, label_html: { class:"label" } %>
          </div>
        </div>
        <div class="field column is-4">
          <div class="control">
            <label class="label">Brand</label>
            <div class="control has-icons-left">
              <span class="select">
                <%= f.input_field :brand, collection: Item::BRAND, prompt: "Select brand" %>
              </span>
              <span class="icon is-small is-left">
                <i class="fa fa-tag"></i>
              </span>
            </div>
          </div>
        </div>
      </div>
      <div class="field">
        <div class="control">
          <label class="label">Add an image</label>
            <div class="file">
            <label class="file-label">
              <%= f.input :image, as: :file, input_html: { class:"file-input item-image" }, label: false, wrapper: false  %>
                <span class="file-cta">
                  <span class="file-icon"><i class="fa fa-upload"></i></span>
                  <span class="file-label">Choose a file…</span>
                </span>
            </label>
            </div>
          </div>
        </div>
        <output id="list"></output>
      <hr />
      <div class="field is-grouped">
        <div class="control">
          <%= f.button :submit, class: 'button is-warning', data: { disable_with: "processing..."} %>
          <%= link_to 'Cancel', items_path, class:'button is-light' %>
        </div>
      </div>
    <% end %>
  </div>
</div>
<script>
  document.addEventListener("turbolinks:load", function() {

    var instrumentImage = document.querySelector('.item-image');

    function handleFileSelect(evt) {
      var files = evt.target.files; // FileList object

      // Loop through the FileList and render image files as thumbnails.
      for (var i = 0, f; f = files[i]; i++) {

        // Only process image files.
        if (!f.type.match('image.*')) {
          continue;
        }

        var reader = new FileReader();

        // Closure to capture the file information.
        reader.onload = (function(theFile) {
          return function(e) {
            // Render thumbnail.
            var span = document.createElement('span');
            span.innerHTML = ['<img class="item-preview-thumb" src="', e.target.result,
              '" title="', escape(theFile.name), '"/>'
            ].join('');
            document.getElementById('list').insertBefore(span, null);
          };
        })(f);
        // Read in the image file as a data URL.
        reader.readAsDataURL(f);
      }
    }

    if (instrumentImage) {
      this.addEventListener('change', handleFileSelect, false);
    }

  });
</script>

app/views/items/_horizontal_scrolling_cards_large.html.erb
<div class="underlined-header col-sm-12 pt-5 container">
  <h4><span>Jewelery you'll love</span> made with passion</h4>
  <p class="text-muted">
    Custom and unique pieces made in Florida
 <!--  Let us take the stress away and ensure you're time on your yacht is just for fun -->
</p>
</div>
<div class="media-scroller snaps-inline mx-5">
  <%= link_to items_path do %>
    <div class="media-element">
        <img src="https://res.cloudinary.com/dk6tfvphu/image/upload/v1655746172/jackie-tsang-3_YP8_mh-Kg-unsplash_luuqq7.jpg" alt="tools">
        <p class="title">All items</p>
    </div>
  <% end %>
  <% if user_signed_in? %>
    <%= link_to new_item_path do %>
      <div class="media-element">
        <img src="https://images.unsplash.com/photo-1642543348791-b1cc1b07e756?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MnwxNDU4OXwwfDF8cmFuZG9tfHx8fHx8fHx8MTY0MzM5ODcyOA&ixlib=rb-1.2.1&q=80&w=400" alt="Sell">
        <p class="title">Sell items</p>
      </div>
    <% end %>
  <% end %>
  <%= link_to items_path do %>
    <div class="media-element">
      <img src="https://res.cloudinary.com/dk6tfvphu/image/upload/v1655746218/rodri-caruso-UDrb3Bud44Y-unsplash_dgpojv.jpg" alt="Engine">
      <p class="title">Placeholder</p>
    </div>
  <% end %>
  <%= link_to items_path do %>
    <div class="media-element">
      <img src="https://res.cloudinary.com/dk6tfvphu/image/upload/v1655746218/christopher-burns-8KfCR12oeUM-unsplash_un82zz.jpg" alt="Nuts and bolts">
      <p class="title">Placeholder</p>
    </div>
  <% end %>
  <%= link_to items_path do %>
    <div class="media-element">
      <img src="https://res.cloudinary.com/dk6tfvphu/image/upload/v1655746217/eleonora-JcL5sCUnBeI-unsplash_yikgsa.jpg" alt="Oils">
      <p class="title">Placeholder</p>
    </div>
  <% end %>
  <%= link_to items_path do %>
    <div class="media-element">
      <img src="https://images.unsplash.com/photo-1484239398315-f1681ef72fe6?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MnwxNDU4OXwwfDF8cmFuZG9tfHx8fHx8fHx8MTY0MzM5ODcyOA&ixlib=rb-1.2.1&q=80&w=400" alt="Merchandise">
      <p class="title">Placeholder</p>
    </div>
  <% end %>
  <%= link_to items_path do %>
    <div class="media-element">
      <img src="https://images.unsplash.com/photo-1620287341401-e2945a4b9daa?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MnwxNDU4OXwwfDF8cmFuZG9tfHx8fHx8fHx8MTY0MzM5ODcyOA&ixlib=rb-1.2.1&q=80&w=400" alt="Contact">
      <p class="title">Contact us</p>
    </div>
  <% end %>
</div>
<style>
  .underlined-header h4 {
    position: relative;
    padding:0;
    color:#007cc7;
    line-height: 1;
    letter-spacing:0.3px;
    font-size: 34px;
    font-weight: 700;
    text-align:center;
    text-transform:none;
    margin-bottom:30px;
  }

  .underlined-header h4:before {
    content: '';
    width: 260px;
    height: 3px;
    background: #007cc7;
    position: absolute;
    left: 0px;
    bottom: -10px;
    right:0;
    margin:0 auto;
  }
  .underlined-header h4 span {
    font-weight: 700;
    padding-bottom: 5px;
    color:#2f2f2f;
  }

  .underlined-header p {
      color:#818181;
      font-size:16px;
      line-height:28px;
      text-align:center;
    }

  .small-underlined-header h4 {
    position: relative;
    padding:0;
    color:#007cc7;
    line-height: 1;
    letter-spacing:0.3px;
    font-size: 16px;
    font-weight: 700;
    text-align:center;
    text-transform:none;
    margin-bottom:30px;
  }

  .small-underlined-header h4:before {
    content: '';
    width: 100px;
    height: 3px;
    background: #007cc7;
    position: absolute;
    left: 0px;
    bottom: -10px;
    right:0;
    margin:0 auto;
  }
  .small-underlined-header h4 span {
    font-weight: 700;
    padding-bottom: 5px;
    color:#2f2f2f;
  }

  .small-underlined-header p {
    // color:#818181;
    font-size:34px;
    line-height:28px;
    text-align:center;
  }
</style>

app/views/items/_horizontal_scrolling_cards_small.html.erb
<h2 class="section-title">Groups elements</h2>
<div class="media-scroller media-scroller--with-groups snaps-inline">

  <!--   Group 1 -->
  <div class="media-group">
    <div class="media-element">
      <img src="https://images.unsplash.com/photo-1641353989082-9b15fa661805?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MnwxNDU4OXwwfDF8cmFuZG9tfHx8fHx8fHx8MTY0MzM5ODcyOA&ixlib=rb-1.2.1&q=80&w=400" alt="">
    </div>
    <div class="media-element">
      <img src="https://images.unsplash.com/photo-1642190672487-22bde32965f7?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MnwxNDU4OXwwfDF8cmFuZG9tfHx8fHx8fHx8MTY0MzM5ODcyOA&ixlib=rb-1.2.1&q=80&w=400" alt="">
    </div>
    <div class="media-element">
      <img src="https://images.unsplash.com/photo-1641841344411-49dbd02896f4?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MnwxNDU4OXwwfDF8cmFuZG9tfHx8fHx8fHx8MTY0MzM5ODcyOA&ixlib=rb-1.2.1&q=80&w=400" alt="">
    </div>
    <div class="media-element">
      <img src="https://images.unsplash.com/photo-1643223723262-7ce785730cf6?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MnwxNDU4OXwwfDF8cmFuZG9tfHx8fHx8fHx8MTY0MzM5ODcyOA&ixlib=rb-1.2.1&q=80&w=400" alt="">
    </div>
    <div class="media-element">
      <img src="https://images.unsplash.com/photo-1640938776314-4d303f8a1380?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MnwxNDU4OXwwfDF8cmFuZG9tfHx8fHx8fHx8MTY0MzM5ODc2Mw&ixlib=rb-1.2.1&q=80&w=400" alt="">
    </div>
  </div>

  <!-- Group 2   -->
  <div class="media-group">
    <div class="media-element">
      <img src="https://images.unsplash.com/photo-1641259041823-e09935369105?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MnwxNDU4OXwwfDF8cmFuZG9tfHx8fHx8fHx8MTY0MzM5ODc2Mw&ixlib=rb-1.2.1&q=80&w=400" alt="">
    </div>
    <div class="media-element">
      <img src="https://images.unsplash.com/photo-1642543492481-44e81e3914a7?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MnwxNDU4OXwwfDF8cmFuZG9tfHx8fHx8fHx8MTY0MzM5ODc2Mw&ixlib=rb-1.2.1&q=80&w=400" alt="">
    </div>
    <div class="media-element">
      <img src="https://images.unsplash.com/photo-1641118961077-440391095cdc?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MnwxNDU4OXwwfDF8cmFuZG9tfHx8fHx8fHx8MTY0MzM5ODc2Mw&ixlib=rb-1.2.1&q=80&w=400" alt="">
    </div>
    <div class="media-element">
      <img src="https://images.unsplash.com/photo-1640767014413-b7d27c58b058?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MnwxNDU4OXwwfDF8cmFuZG9tfHx8fHx8fHx8MTY0MzM5ODc5NQ&ixlib=rb-1.2.1&q=80&w=400" alt="">
    </div>
    <div class="media-element">
      <img src="https://images.unsplash.com/photo-1640948612546-3b9e29c23e98?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MnwxNDU4OXwwfDF8cmFuZG9tfHx8fHx8fHx8MTY0MzM5ODc5NQ&ixlib=rb-1.2.1&q=80&w=400" alt="">
    </div>
  </div>

  <!-- Group 3   -->
  <div class="media-group">
    <div class="media-element">
      <img src="https://images.unsplash.com/photo-1642484865851-111e68695d71?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MnwxNDU4OXwwfDF8cmFuZG9tfHx8fHx8fHx8MTY0MzM5ODc5NQ&ixlib=rb-1.2.1&q=80&w=400" alt="">
    </div>
    <div class="media-element">
      <img src="https://images.unsplash.com/photo-1642237778207-24985a0bf876?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MnwxNDU4OXwwfDF8cmFuZG9tfHx8fHx8fHx8MTY0MzM5ODc5NQ&ixlib=rb-1.2.1&q=80&w=400" alt="">
    </div>
    <div class="media-element">
      <img src="https://images.unsplash.com/photo-1642177584449-fa0b017dccc7?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MnwxNDU4OXwwfDF8cmFuZG9tfHx8fHx8fHx8MTY0MzM5ODc5NQ&ixlib=rb-1.2.1&q=80&w=400" alt="">
    </div>
    <div class="media-element">
      <img src="https://images.unsplash.com/photo-1643249960396-d39d2a63ce8a?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MnwxNDU4OXwwfDF8cmFuZG9tfHx8fHx8fHx8MTY0MzM5ODg0Mw&ixlib=rb-1.2.1&q=80&w=400" alt="">
    </div>
    <div class="media-element">
      <img src="https://images.unsplash.com/photo-1641424222187-1c336d21804c?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MnwxNDU4OXwwfDF8cmFuZG9tfHx8fHx8fHx8MTY0MzM5ODg0OA&ixlib=rb-1.2.1&q=80&w=400" alt="">
    </div>
  </div>

  <!--  Group 4  -->
  <div class="media-group">
    <div class="media-element">
      <img src="https://images.unsplash.com/photo-1640998483268-d1faffa789ad?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MnwxNDU4OXwwfDF8cmFuZG9tfHx8fHx8fHx8MTY0MzM5ODkwNA&ixlib=rb-1.2.1&q=80&w=400" alt="">
    </div>
    <div class="media-element">
      <img src="https://images.unsplash.com/photo-1642034451735-2a8df1eaa2c0?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MnwxNDU4OXwwfDF8cmFuZG9tfHx8fHx8fHx8MTY0MzM5ODg4OQ&ixlib=rb-1.2.1&q=80&w=400" alt="">
    </div>
    <div class="media-element">
      <img src="https://images.unsplash.com/photo-1640808238224-5520de93c939?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MnwxNDU4OXwwfDF8cmFuZG9tfHx8fHx8fHx8MTY0MzM5ODg4OQ&ixlib=rb-1.2.1&q=80&w=400" alt="">
    </div>
    <div class="media-element">
      <img src="https://images.unsplash.com/photo-1643039952431-38adfa91f320?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MnwxNDU4OXwwfDF8cmFuZG9tfHx8fHx8fHx8MTY0MzM5ODg0OA&ixlib=rb-1.2.1&q=80&w=400" alt="">
    </div>
    <div class="media-element">
      <img src="https://images.unsplash.com/photo-1643148636637-58b3eb95cdad?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MnwxNDU4OXwwfDF8cmFuZG9tfHx8fHx8fHx8MTY0MzM5ODg0OA&ixlib=rb-1.2.1&q=80&w=400" alt="">
    </div>
  </div>

</div>

app/views/items/edit.html.erb
<h1>Editing Item</h1>

<%= render 'form', item: @item %>

<%= link_to 'Show', @item %> |
<%= link_to 'Back', items_path %>

app/views/items/index.html.erb
<!--
</% if user_signed_in? %>
  </%= link_to 'New Item', new_item_path %>
</% end %> -->
<!-- render the scrolling cards partial -->
<% if current_page?(root_path) %>
  <%= render "horizontal_scrolling_cards_large" %>
<% end %>
<!-- for smaller cards elements - use below -->
<!-- </%= render "horizontal_scrolling_cards_small" %> -->
<!-- Below is code for the meilisearch search bar -->
<!-- <div class="mt-3" style="max-width:400px">
  <form class="d-flex">
  </%= form_with url: items_path, method: :get do |form| %>
    </%= form.search_field :query, class: "form-control me-2", type: "search", placeholder: "Search" %>
    </%= form.button "Search", class: "btn btn-outline-success", type: "submit" %>
  </% end %>
</form>
</div> -->
<% if current_page?(items_path) %>
  <div class="item-index-grid pt4 is-desktop">
    <% @items.each do |item| %>
      <div class="item border-light-color">
        <div class="item-thumb">
        <%= link_to image_tag(item.image_url(:thumb)), item %>
          <div class="available">
            <span class="tag" style="background-color: #b70705; color: white;"><%= product_availability(item) %></span>
          </div>
        </div>
      <div class="pa3">
        <h3 class="fw7 f4 title"><%= link_to item.title, item %></h3>
        <p class="has-text-gray fg pt1">Sold by <%= item.user.first_name %> <%= item.user.last_name %></p>
        <p class="f3 fw6 has-text-right pt2 price"><%= number_to_currency(item.price) %></p>
        <% if allowed_to_edit(item) %>
           <%= link_to 'Edit', edit_item_path(item), class: "button is-small" %>
           <%= link_to 'Delete', item, method: :delete, data: { confirm: "Are you sure ?" }, class: "button is-small" %>
        <% end %>
      </div>
    </div>
    <% end %>
  </div>
  <div class="pt-3 pb-3">
    <%== pagy_bootstrap_nav(@pagy) %>
  </div>
<% end %>

 <!-- </%= form_with url: items_path, method: :get, do |form| %>
   </%= form.search_field :query %>
   </%= form.button "Search" %>
 </% end %> -->
<!--
</% if current_page?(items_path) %>
    <div class="row">
  </% @items.each do |item| %>
      <div class=" col-xs-6 col-sm-4 col-md-3  col-lg-3">

        <div class="item border-light-color">
          <div class="item-thumb">
          </%= link_to image_tag(item.image_url(:thumb)), item %>
            <div class="available">
              <span class="tag" style="background-color: #b70705; color: white;"></%= product_availability(item) %></span>
            </div>
          </div>
        <div class="pa3">
          <h3 class="fw7 f4 title"></%= link_to item.title, item %></h3>
          <p class="has-text-gray fg pt1">Sold by </%= item.user.first_name %> </%= item.user.last_name %></p>
          <p class="f3 fw6 has-text-right pt2 price"></%= number_to_currency(item.price) %></p>
          </% if allowed_to_edit(item) %>
             </%= link_to 'Edit', edit_item_path(item), class: "button is-small" %>
             </%= link_to 'Delete', item, method: :delete, data: { confirm: "Are you sure ?" }, class: "button is-small" %>
          </% end %>
        </div>
      </div>
      </div>
    </% end %>
    </div>
  </div>
  <div class="pt-3 pb-3">
    </%== pagy_bootstrap_nav(@pagy) %>
  </div>
</% end %>
-->

app/views/items/new.html.erb
<div class="col-8">
  <div class="container pt-3 pb-3">
    <div class="card">
      <div class="card-header">
        <h2>New Item</h2>
      </div>
      <div class="card-body">
        <%= render 'form', item: @item %>
        <%= link_to 'Back', items_path %>
      </div>
    </div>
  </div>
</div>

app/views/items/show.html.erb
<% content_for :body_class, 'bg-grey' %>
<div class="show_page">
  <section class="section item-show">
    <div class="row">
      <div class="col-md-12 col-lg-8">
        <h1 class="title is-2"><%= @item.title %></h1>
        <div class="row ps-5">
          <div class="col-2">Product code:</div>
          <div class="col-2"><%= @item.product_code %></div>
        </div>
        <div class="row ps-5">
          <div class="col-2">Reviews: </div>
          <div class="col-2"><%= @item.review_count %></div>
        </div>
        <div class="row ps-5 pb-5">
          <div class="col-2">Review Rating:</div>
          <div class="col-2">
            <div class="star_rating">
              <div class="stars-outer">
                <div class="stars-inner"></div>
              </div>
            </div>
          </div>
        </div>
        <script>
          var ratings = {
            star_rating : <%= @item.review_rating %>,
          };
          // total number of stars
          var starTotal = 5;
          for(var rating in ratings) {
            var starPercentage = (ratings[rating] / starTotal) * 100;
            var starPercentageRounded = `${(Math.round(starPercentage / 10) * 10)}%`;
            document.querySelector(`.${rating} .stars-inner`).style.width = starPercentageRounded;
          }
        </script>
        <div class="feature-image" style="widows: 100%;">
          <%= image_tag(@item.image_url(:default)) %>
        </div>
        <div class="content pa4 mt3 bg-white border-radius-3">
          <h3 class="subtitle is-4">Description</h3>
          <%= @item.description %>
          <h3 class="subtitle is-4 pt5">Product Specs</h3>
          <table class="table is-narrow">
            <% if @item.product_code %>
            <tr>
              <td class="has-text-weight-bold">Product code:</td>
              <td><%= @item.product_code %></td>
            </tr>
            <% end %>
            <% if @item.availability %>
              <tr>
                <td class="has-text-weight-bold">Availability:</td>
                <td><%= product_availability(@item) %></td>
              </tr>
            <% end %>
            <% if @item.availability != "0" %>
              <tr>
                <td class="has-text-weight-bold">Amount in stock:</td>
                <td><%= @item.quantity_available %></td>
              </tr>
            <% end %>
            <% if @item.price %>
              <tr>
                <td class="has-text-weight-bold">Price:</td>
                <td><%= number_to_currency(@item.price) %></td>
              </tr>
            <% end %>
            <tr>
              <td class="has-text-weight-bold">Brand:</td>
              <td><%= @item.brand %></td>
            </tr>
          </table>
        </div>
      </div>
      <div class="col-md-12 col-lg-4 p-3">
        <div class="bg-white pa4 border-radius-3">
          <h4 class="title is-5 has-text-centered"><%= number_to_currency(@item.price) %></h4>
          <p class="has-text-centered mb4">Sold by <%= @item.user.first_name %> <%= @item.user.last_name %></p>
          <% if @item.quantity_available == "0" %>
            <%= link_to 'None in stock', items_path, class: 'button is-warning add-to-cart', style: "width: 100%;" %>
          <% elsif user_signed_in? %>
            <%= button_to 'Add to cart', line_items_path(item_id: @item), class: 'button is-warning add-to-cart', style: "width: 100%;" %>
          <% else %>
            <%= link_to "Sign Up/Log in to add", new_user_registration_path, class: 'button is-warning add-to-cart', style: "width: 100%;" %>
          <% end %>
        </div>
      </div>
    </div>
  </section>
</div>